### ISSUE TITLE
Peer review week 1

### ISSUE THREAD

**Issue by norakramer1** [Yolandaokyere/ArtLibrary#2]
## Repo
Repo ziet er netjes uit, alle namen zijn duidelijk aangegeven. Er staan wel veel mapjes in je project misschien kun je alleen de hoofdopdracht in de repo zetten. Ook kun je aantekeningen en informatie opschrijven in je wiki zodat alles op een plek staat.

Je zou ook in je readme informatie over het project kunnen geven. Misschien meer vertellen over hoe gebruikers die jou project tegen komen er verder op kunnen bouwen door info te geven over de API keys bijvoorbeeld.

Ik kan ook je live site niet zien met de link op dit moment.

## Code
De code is duidelijk te begrijpen, de namen voor variabelen zijn duidelijk en zeggen iets over hoe ze gebruikt worden.

Je zou met de RijksData api in de link kunnen aangeven hoeveel resultaten je wilt fetchen. Het is niet nodig om alle resultaten elke keer op te halen (maar dat is eigen voorkeur!). Je link ziet er nu zo uit:
```
const endpoint = 'https://www.rijksmuseum.nl/api/nl/collection/?key=GnjcnmeH'; 
```

Als je van de link dit zou maken:

```
const endpoint = 'https://www.rijksmuseum.nl/api/nl/collection/?key=GnjcnmeH'&ps=10';
``` 
Krijg je 10 resultaten terug. Dit komt omdat je parameters mee kan geven aan de link die informatie geven over wat je terug wilt krijgen, zou je van `ps=10` `ps=100` maken zou je 100 resultaten terugkrijgen. 

Op regel 52 word nu 

```
document.body.style.backgroundColor = 'red';  
```
Het is het beste dat stijl zoveel mogelijk aangegeven word in de CSS om zo tekst, stijl en interactie apart te houden.

Voor de rest ziet het er nice uit! Echt goed dat je zo ver gekomen bent !

**Comment by Yolandaokyere** [comment]
> ## Repo
> Repo ziet er netjes uit, alle namen zijn duidelijk aangegeven. Er staan wel veel mapjes in je project misschien kun je alleen de hoofdopdracht in de repo zetten. Ook kun je aantekeningen en informatie opschrijven in je wiki zodat alles op een plek staat.
>  
> Je zou ook in je readme informatie over het project kunnen geven. Misschien meer vertellen over hoe gebruikers die jou project tegen komen er verder op kunnen bouwen door info te geven over de API keys bijvoorbeeld.
> 
> Ik kan ook je live site niet zien met de link op dit moment.
> 
> ## Code
> De code is duidelijk te begrijpen, de namen voor variabelen zijn duidelijk en zeggen iets over hoe ze gebruikt worden.
> 
> Je zou met de RijksData api in de link kunnen aangeven hoeveel resultaten je wilt fetchen. Het is niet nodig om alle resultaten elke keer op te halen (maar dat is eigen voorkeur!). Je link ziet er nu zo uit:
> 
> ```
> const endpoint = 'https://www.rijksmuseum.nl/api/nl/collection/?key=GnjcnmeH'; 
> ```
> 
> Als je van de link dit zou maken:
> 
> ```
> const endpoint = 'https://www.rijksmuseum.nl/api/nl/collection/?key=GnjcnmeH'&ps=10';
> ```
> 
> Krijg je 10 resultaten terug. Dit komt omdat je parameters mee kan geven aan de link die informatie geven over wat je terug wilt krijgen, zou je van `ps=10` `ps=100` maken zou je 100 resultaten terugkrijgen.
> 
> Op regel 52 word nu
> 
> ```
> document.body.style.backgroundColor = 'red';  
> ```
> 
> Het is het beste dat stijl zoveel mogelijk aangegeven word in de CSS om zo tekst, stijl en interactie apart te houden.
> 
> Voor de rest ziet het er nice uit! Echt goed dat je zo ver gekomen bent !

**Comment by Yolandaokyere** [comment]
Dankjewel voor de tips!
Ik heb er nu 100 kunnen inladen i.p.v 10, ik kon er niet meer dan 100 krijgen
Heb ook stiekem afgekeken bij de repo's van vorig jaar die ziet er nu beter uit dan vorige week
De stijl heb ik nu allemaal overgezet in mijn css dankjewel!🥰
