### ISSUE TITLE
Peerfeedback

### ISSUE THREAD

**Issue by timmit147** [Yolandaokyere/ArtLibrary#3]
## Code
Ik heb geen opmerkingen over de code omdat het meeste al is gezegd in een andere issue. Het belangrijkste is vooral de afbeeldingen minder groot ophalen uit de API zodat de website niet zo langzaam werkt.

## Styling pagina
Op mobiel kan je de titel mischien breder maken

![image](https://user-images.githubusercontent.com/29665951/156622420-b670d06d-8676-4410-94be-8eefd9258436.png)

Ik vind de tekst en de afbeeldingen veel naar de rand mischien de ol een padding geven van 50px;
![image](https://user-images.githubusercontent.com/29665951/156622816-1d08e70e-a6e1-4515-91ba-19dbf84a7175.png)

Input veld mischien meer padding
![image](https://user-images.githubusercontent.com/29665951/156623953-205486bb-2cc4-44b1-9647-f63b818e960b.png)

Ik vind persoonlijk het zoekveld mooier als het aan de linker kant staat omdat je ook van links naar rechts leest.
#zoek-met-button form {
    flex-grow: 1;
    display: flex;
    justify-content: flex-start;
}
![image](https://user-images.githubusercontent.com/29665951/156624240-ad89a52b-b937-4907-96d8-881245476459.png)

Styling van de website ziet er goed uit.

**Comment by Yolandaokyere** [comment]
Thanks for the feedback!! styling ziet er veel beter uit nu
Heb de titel groter gemaakt en de padding aangepast zodat deze op mobiele ook goed uitziet en niet meer tegen de randjes aanzit!  
![2022-03-07 (16)](https://user-images.githubusercontent.com/97689634/156949009-64ff26b2-9fa9-410a-9a0f-00909ad0e5fe.png)

searchbar ook aangepast 🥰 
![2022-03-07 (20)](https://user-images.githubusercontent.com/97689634/156949137-0bb22651-9104-47c9-bf80-577e10c162b3.png)
